language: python
python:
  - 2.6
  - 2.7
  - 3.3

env:
  matrix: 
    - ADDITIONAL_SETUP="pip install flux"
    - ADDITIONAL_SETUP="true"
install: 
  - python setup.py develop
  - python scripts/test_setup.py
  - "$ADDITIONAL_SETUP"
# command to run tests, e.g. python setup.py test
script: nosetests -w tests